Need to include cpu_accel.h to prevent this:
ontheflyratectl.cc: In method `void OnTheFlyRateCtl::InitNewPict(Picture &)':
ontheflyratectl.cc:409: implicit declaration of function `int fmax(...)'
gmake[2]: *** [ontheflyratectl.lo] Error 1

from happening on systems which lack fmax().